# Generated by Django 5.0.2 on 2024-02-19 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AlterField(
            model_name='price',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='stocks.stock'),
        ),
    ]
