# Generated by Django 5.0.2 on 2024-02-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_price_volume_investment_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='date',
        ),
        migrations.AddField(
            model_name='investment',
            name='weights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.portfolio'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='price',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=12),
        ),
    ]
