# Generated by Django 5.0.2 on 2024-02-29 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_investment_date_investment_weights_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='number_of_shares',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='weights',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='stocks',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='value',
        ),
        migrations.AddField(
            model_name='investment',
            name='date',
            field=models.DateField(default='None'),
        ),
        migrations.AddField(
            model_name='investment',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='weight',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='stocks.portfolio'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
