# Generated by Django 5.0.2 on 2024-02-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_investment_number_of_shares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
