# Generated by Django 5.0.2 on 2024-02-29 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_investment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='investment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
