# Generated by Django 5.0.2 on 2024-02-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_investment_date_alter_investment_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
