# Generated by Django 5.0.2 on 2024-02-29 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_investment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
